---
- name: Create VMs
  hosts: localhost
  vars_prompt:
  - name: network
    prompt: Network?
    private: false
  tasks:
  - include_role: 
      name: instances
    tags: 
    - ssh_config

- name: Configure VMs
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - include_role:
      name: configuration
    tags:

- name: Cleanup
  hosts: localhost
  gather_facts: false
  tasks:
  - include_role:
      name: cleanup

- name: Update SSH config
  hosts: localhost
  gather_facts: true
  tasks:
  - include_role:
      name: ssh
    tags:
    - ssh_config
    