---
- name: Create VMs
  hosts: localhost
  vars_prompt:
  - name: network
    prompt: Network?
    private: false
  tasks:
  # Include this role to gather information about instances before assigning Floating IP>
  # Needed for tags hosts and keys
  - include_role:
      name: instances
    tags:
    - hosts
    - keys
    when: "'hosts' in ansible_run_tags or 'keys' in ansible_run_tags"
  
  # Add a floating IP to the instances to reconfigure them.
  # Needed for tags hosts and keys
  - include_role:
      name: floatingip
    tags:
    - hosts
    - keys
    when: "'hosts' in ansible_run_tags or 'keys' in ansible_run_tags"
    
  - include_role: 
      name: instances
    tags: 
    - ssh_config
    - hosts
    - keys

- name: Configure VMs
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - include_role:
      name: configuration
  tags:
  - hosts
  - keys

- name: Cleanup
  hosts: localhost
  gather_facts: false
  tasks:
  - include_role:
      name: cleanup
  tags:
  - hosts
  - keys

- name: Update SSH config
  hosts: localhost
  gather_facts: true
  tasks:
  - include_role:
      name: ssh
    tags:
    - ssh_config
    