--- 
- name: Wait before connecting to host
  wait_for_connection:
    delay: 15
    timeout: 30

- name: Copy public key
  ansible.builtin.copy:
    src: id_rsa-jh.pub
    dest: /home/{{ user }}/.ssh/id_rsa-jh.pub
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

- name: Set authorized key taken from files
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob: "keys/*"

- name: Enumerate all cluster hosts within the /etc/hosts file
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: JumpHost examples Hosts"
    content: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host_private_ipv4'] }} {{ host }}
      {% endfor %}
