- name: Create security group
  openstack.cloud.security_group:
    state: present
    name: "jumphost-security-group"
    description: "Security group for jumphost"

- name: Add port 22 opening to ips {{ internal_ips }} to rule {{ instance_name }}
  openstack.cloud.security_group_rule:
    state: "{{ state }}"
    security_group: "{{ instance_name }}-security-group"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ item }}"
  with_items:
    - "{{ internal_ips }}"

- name: Add port 80 opening to rule {{ instance_name }}
  openstack.cloud.security_group_rule:
    state: "{{ state }}"
    security_group: "{{ instance_name }}-security-group"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

## default Security Group
- openstack.cloud.security_group_rule:
    security_group: "{{ instance_name }}-security-group"
    state: "{{ state }}"
    direction: egress
    protocol: any
    remote_ip_prefix: 0.0.0.0/0
  when: ansible_facts['distribution'] == "MacOSX"

- openstack.cloud.security_group_rule:
    state: "{{ state }}"
    security_group: "{{ instance_name }}-security-group"
    ethertype: IPv6
    direction: egress
    protocol: any
    remote_ip_prefix: ::/0
  when: ansible_facts['distribution'] == "MacOSX" 
