---
- name: Add Floating IPs to instances
  openstack.cloud.floating_ip:
    state: present
    reuse: true
    server: "{{ hostvars[item]['inventory_hostname'] }}"
  with_items: 
  - "{{ groups['instances_group'] }}"
  when: not state is search("absent")
  tags:
  - hosts
  - keys